from __future__ import unicode_literals
from django.shortcuts import render
from django.http import HttpResponse
from django.http import JsonResponse
from .models import WebAppMeta

import socket
import json

from datetime import datetime


def json(request):
    data = list(WebAppMeta.objects.values())
    return JsonResponse(data, safe=False)

def index(request):
    # return HttpResponse("<h1>Hello, world !</h1>")
    # Some Date Object, for example a default generated by datetime
    myDate = datetime.now()
    
    # Give a format to the date
    # Displays something like: Aug. 27, 2017, 2:57 p.m.
    formatedDate = myDate.strftime("%Y-%m-%d %H:%M:%S")

    # Do something with the formatted date
    return JsonResponse(formatedDate,safe=False)

# Function to display hostname and
# IP address
def get_Host_name_IP():
    try:
        host_name = socket.gethostname()
        host_ip = socket.gethostbyname(host_name)
        print("Hostname :  ",host_name)
        print("IP : ",host_ip)
    except:
        print("Unable to get Hostname and IP")
 
# Driver code
    return JsonResponse(get_Host_name_IP(), safe=False)#Function call
 

def visitor_ip_address(request):

    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')

    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return JsonResponse(ip, safe=False)


 
